### PR TITLE
add metadata and fix the issue #6

### LINKED ISSUE #6: Unable to get Token info(getTokenInfo)
Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Badly formed object around character 29." UserInfo={NSDebugDescription=Badly formed object around character 29.}))): file Pokepay/Pokepay.swift, line 126

### PR DESCRIPTION
**Pull request by WeiWW**

### CODE REVIEW

File: lib/responses/token_info.dart [hunk 1]
```diff
@@ -21,7 +20,7 @@ class TokenInfo extends Response {
   @JsonKey(nullable: false)
   final TokenType type;
   @JsonKey(nullable: false)
-  final String token;
+  final dynamic token;
```
Comment (taniryo-kun) [inline lib/responses/token_info.dart:23]: what is dynamic?
couldn't understand why this has to change from String

**Review by taniryo-kun — COMMENTED** [review]
are there any test codes?

File: lib/responses/token_info.dart (hunk 1 above)
Comment (WeiWW) [reply lib/responses/token_info.dart:23]: https://github.com/pokepay/flutter-sdk/blob/bf99f02bce497badb9969a4dcf716155845fed40/lib/pokepay_sdk.dart#L185

Because when the token is from `Bill`, `Check` and `CPM`, this will be  `Bill`, `Check` and `CPM` separately; if the token is from `Cashtray`, `PAYREGI` or unknown, this will be an empty string.

**Comment by WeiWW** [comment]
> are there any test codes?

The test in the [internal project](https://github.com/pokepay/flutter-sdk-internal/blob/b6a8c353b316d6afba69a98af3f97efaaf449e42/example/test/low_level_api/account.dart#L48), here only are flutter source code.

File: lib/responses/token_info.dart (hunk 1 above)
Comment (taniryo-kun) [reply lib/responses/token_info.dart:23]: So its String or empty, right?
`dynamic` is more like a wildcard so if its possible you shouldn't use this type.

**Comment by taniryo-kun** [comment]
> The test in the internal project, here only are flutter source code.

checked the test code!

**Review by taniryo-kun — CHANGES_REQUESTED** [review]
commented

File: lib/responses/token_info.dart (hunk 1 above)
Comment (WeiWW) [reply lib/responses/token_info.dart:23]: No, it will be String, `Bill`, `Check` or `CPM`, like in [Android](https://github.com/pokepay/android-sdk/blob/baa47f8509fe5c77c41f9cb63ad37c9fb8e9850d/pokepaylib/src/main/java/jp/pokepay/pokepaylib/TokenInfo.java#L13) and [iOS](https://github.com/pokepay/ios-sdk/blob/master/Sources/Pokepay/Responses/TokenInfo.swift)

Comment (taniryo-kun) [reply lib/responses/token_info.dart:23]: @WeiWW  so its not a token string itself, but a TokenInfo Object (or empty String)?
It could be better if we could use like a type `TokenInfo?`.  (because empty string means nothing and types like dynamic or any is a little smelly code, you know)

**Review by taniryo-kun — APPROVED** [review]
I added one comment. Other than that looks ok

File: lib/responses/token_info.dart (hunk 1 above)
Comment (WeiWW) [reply lib/responses/token_info.dart:23]: @taniryo-kun I think this would be open another issue for this because currently both [Android](https://github.com/pokepay/android-sdk/blob/baa47f8509fe5c77c41f9cb63ad37c9fb8e9850d/pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java#L85) and [iOS](https://github.com/pokepay/ios-sdk/blob/6b8cc37c63c3754d48fa59a36f5043ac27fdfd6c/Sources/Pokepay/Pokepay.swift#L100) are doing the same way.
